/**
 * Determinism test — two matches with the same seed have to be the same match.
 *
 * Like the project's other tests, it runs in the browser:
 *
 * ```js
 * const t = await import('/tests/determinism.ts');
 * console.table((await t.runDeterminismTests()).cases);
 * ```
 *
 * **What gets proved here, and why it is the most important of the four.** The whole
 * networked duel rests on a single promise: given the same seed and the same sequence of
 * inputs, two machines arrive at the same state. If that promise fails, none of the
 * netcode works — and the way it fails is the worst possible one, because the divergence
 * starts small, grows on its own and only shows up when the two players are already
 * arguing about which of them saw the right shot.
 *
 * Two complete `Match`es, two environments, one input script. They run side by side for
 * 1800 steps (thirty seconds of duel) and are compared **bit for bit** — with no
 * tolerance, on purpose: any slack here would hide precisely the kind of error that
 * accumulates.
 *
 * The input script is generated by `createRandom`, so it is always the same script. A
 * determinism test with genuinely random input would be a test that only fails sometimes.
 */

import * as THREE from 'three';
import { createRandom } from '../src/core/MathUtils';
import { InputBit, createInputFrame, type InputFrame } from '../src/core/InputFrame';
import { QUALITY_PRESETS } from '../src/core/Settings';
import { Match, type MatchInputs } from '../src/game/Match';
import { Environment } from '../src/world/Environment';

export interface TestCase {
  nome: string;
  medido: string;
  esperado: string;
  erro: string;
  passou: boolean;
}

export interface TestReport {
  passou: boolean;
  total: number;
  falhas: number;
  cases: TestCase[];
}

/**
 * Simulated steps. 5400 at 60 Hz is ninety seconds of duel.
 *
 * The number is chosen by the combat's clock, not by taste: the two ships are born 220 m
 * apart and take close to a minute to come into range. At thirty seconds the test passed
 * without a single shot having been fired — and it is precisely in the damage that the
 * two draw streams entering the simulation live (the gunner's aim scatter and the
 * sailor's breach choice). A determinism test that never gets as far as firing does not
 * test what matters.
 */
const TICKS = 5400;

/** The input script's seed. Fixed: see the header. */
const SCRIPT_SEED = 0xd0d0;

/**
 * An input script that **touches everything**.
 *
 * Walking is not enough: the test has to exercise press edges (which is where a badly
 * written sampler loses or repeats commands), station changes, aiming and the trigger.
 * The weights are chosen so the sailor spends most of the time walking and still takes
 * guns regularly.
 */
function buildScript(ticks: number): InputFrame[] {
  const random = createRandom(SCRIPT_SEED);
  const script: InputFrame[] = [];

  let held = 0;
  for (let tick = 0; tick < ticks; tick++) {
    // The held state changes in blocks, and not every step: someone who walks, walks
    // for a while. Changing everything every step would test a player who does not exist
    // and would hide the velocity integration.
    if (tick % 24 === 0) {
      held = 0;
      if (random() < 0.75) held |= InputBit.MoveForward;
      if (random() < 0.2) held |= InputBit.MoveBack;
      if (random() < 0.3) held |= InputBit.MoveLeft;
      if (random() < 0.3) held |= InputBit.MoveRight;
      if (random() < 0.35) held |= InputBit.Sprint;
      if (random() < 0.25) held |= InputBit.Interact;
      if (random() < 0.15) held |= InputBit.Aim;
    }

    let pressedBits = 0;
    if (random() < 0.02) pressedBits |= InputBit.Jump;
    if (random() < 0.03) pressedBits |= InputBit.Interact;
    if (random() < 0.02) pressedBits |= InputBit.Exit;
    // Load and fire often: they are the two actions that put a ball in the air, and it
    // is the ball in the air that takes the test through the damage.
    if (random() < 0.12) pressedBits |= InputBit.Reload;
    if (random() < 0.1) pressedBits |= InputBit.Fire;

    const frame = createInputFrame();
    frame.tick = tick;
    frame.held = held;
    frame.pressed = pressedBits;
    frame.moveX = (held & InputBit.MoveRight ? 1 : 0) - (held & InputBit.MoveLeft ? 1 : 0);
    frame.moveY = (held & InputBit.MoveForward ? 1 : 0) - (held & InputBit.MoveBack ? 1 : 0);
    frame.lookX = (random() - 0.5) * 0.06;
    frame.lookY = (random() - 0.5) * 0.04;
    script.push(frame);
  }

  return script;
}

/**
 * Everything that defines a match's state, flattened into a list of numbers.
 *
 * Flattening is what allows comparing without writing one comparator per subsystem — and
 * what makes a new field enter the test just by being added here.
 */
function fingerprint(match: Match): number[] {
  const out: number[] = [];

  for (const ship of match.ships) {
    const { body } = ship;
    out.push(body.comPosition.x, body.comPosition.y, body.comPosition.z);
    out.push(body.orientation.x, body.orientation.y, body.orientation.z, body.orientation.w);
    out.push(body.velocity.x, body.velocity.y, body.velocity.z);
    out.push(body.angularVelocity.x, body.angularVelocity.y, body.angularVelocity.z);
    out.push(body.floodedMass);

    out.push(ship.rudder.wheelAngle, ship.rudder.rudderAngle);
    out.push(ship.cannonballs, ship.planks);
    out.push(ship.anchor.deploy, ship.anchor.tension);

    for (const cannon of ship.cannons) {
      out.push(cannon.traverse, cannon.elevation, cannon.recoil, cannon.loadProgress);
      out.push(cannon.state === 'empty' ? 0 : cannon.state === 'loading' ? 1 : 2);
    }

    const { damage } = ship;
    out.push(damage.floodVolume, damage.sinkTime, damage.breaches.length, damage.patches.length);
    for (const breach of damage.breaches) {
      out.push(breach.id, breach.local.x, breach.local.y, breach.local.z);
      out.push(breach.area, breach.repair);
    }
    for (const patch of damage.patches) {
      out.push(patch.id, patch.local.x, patch.local.y, patch.local.z, patch.area);
    }
  }

  for (const crewman of match.crew) {
    const c = crewman.controller;
    out.push(c.local.x, c.local.y, c.local.z);
    out.push(c.velocity.x, c.velocity.y, c.velocity.z);
    out.push(c.yaw, c.pitch);
    out.push(c.station === 'deck' ? 0 : c.station === 'helm' ? 1 : 2);
    out.push(c.cannonIndex, c.grounded ? 1 : 0, c.onLadder ? 1 : 0, c.atCapstan ? 1 : 0);
  }

  const waves = match.environment.waveField;
  out.push(waves.time, waves.windStrength, waves.windDirection, waves.swellDirection);

  out.push(match.tick, match.stats.shotsFired, match.stats.shotsLanded);
  out.push(match.stats.breachesDealt, match.stats.breachesTaken);

  return out;
}

/** An isolated match, with a scene and an environment of its own. */
function createMatch(): { match: Match; dispose: () => void } {
  const scene = new THREE.Scene();
  const environment = new Environment(scene, QUALITY_PRESETS.low, { seed: 1337 });
  const match = new Match(scene, environment);
  return {
    match,
    dispose: () => {
      match.dispose();
      environment.dispose();
    },
  };
}

/** What happened in one run, so case 3 knows whether it was worth anything. */
interface RunResult {
  fingerprint: number[];
  shotsFired: number;
  shotsLanded: number;
  playerHoles: number;
  enemyHoles: number;
}

/**
 * The step from which the sailor is put on the cannon by force.
 *
 * The drawn script walks, jumps, interacts and aims — but **taking a gun** depends on
 * being in the right place pressing the right button, and a random draw almost never gets
 * both. Without this, the player never fired, the enemy ship never took a breach, and the
 * machine's sailor never had to choose which hole to patch: one of the simulation's two
 * draw streams stayed entirely outside the test.
 *
 * The intervention is deterministic — it depends only on the step and the state, which
 * are the same in both runs —, so it does not weaken what is being proved. 900 steps is
 * fifteen seconds: time for the duel to close in first.
 */
const MOUNT_CANNON_AT = 900;

/** Runs the whole script on a match and returns the final fingerprint. */
function run(match: Match, script: readonly InputFrame[]): RunResult {
  match.startSolo('corsair');
  const inputs: MatchInputs = { player: createInputFrame(), enemy: null };
  const mutable = inputs as { player: InputFrame };
  const controller = match.crew[0].controller;

  for (const frame of script) {
    // It remounts whenever the script has left the gun (`Exit` is drawn at random).
    if (frame.tick >= MOUNT_CANNON_AT && controller.station !== 'cannon') {
      controller.mountCannon(frame.tick % 2 === 0 ? 0 : 1);
    }
    mutable.player = frame;
    match.fixedUpdate(1 / 60, inputs);
  }

  return {
    fingerprint: fingerprint(match),
    shotsFired: match.stats.shotsFired,
    shotsLanded: match.stats.shotsLanded,
    playerHoles: match.playerShip.damage.breaches.length,
    enemyHoles: match.enemyShip.damage.breaches.length,
  };
}

export async function runDeterminismTests(): Promise<TestReport> {
  const cases: TestCase[] = [];
  const script = buildScript(TICKS);

  const matchA = createMatch();
  const matchB = createMatch();

  let a: RunResult;
  let b: RunResult;
  try {
    a = run(matchA.match, script);
    b = run(matchB.match, script);
  } finally {
    matchA.dispose();
    matchB.dispose();
  }

  const first = a.fingerprint;
  const second = b.fingerprint;

  // --- 1. both fingerprints have the same size --------------------------------
  cases.push({
    nome: 'fingerprint · same number of fields',
    medido: `${first.length}`,
    esperado: `${second.length}`,
    erro: first.length === second.length ? '—' : 'breach lists diverged',
    passou: first.length === second.length,
  });

  // --- 2. bit for bit, with no tolerance --------------------------------------
  let mismatches = 0;
  let worst = 0;
  let worstIndex = -1;
  const shared = Math.min(first.length, second.length);
  for (let i = 0; i < shared; i++) {
    const delta = Math.abs(first[i]! - second[i]!);
    if (delta === 0) continue;
    mismatches++;
    if (delta > worst) {
      worst = delta;
      worstIndex = i;
    }
  }

  cases.push({
    nome: `${TICKS} steps · identical state`,
    medido: `${mismatches} diverging fields`,
    esperado: '0 diverging fields',
    erro:
      mismatches === 0
        ? '—'
        : `worst: field ${worstIndex}, Δ ${worst.toExponential(3)}`,
    passou: mismatches === 0,
  });

  // --- 3. the script actually did something -----------------------------------
  // A determinism test passes trivially if nothing happens. This case is what keeps the
  // test from becoming decoration the day the script stops touching the game — two ships
  // sitting still are identical and prove nothing.
  const moved = Math.hypot(first[0]!, first[2]!);
  const shots = a.shotsFired + a.shotsLanded;
  const holes = a.playerHoles + a.enemyHoles;
  cases.push({
    nome: 'script · the duel actually happened',
    medido: `${moved.toFixed(1)} m · ${shots} shots · ${holes} breaches`,
    esperado: '> 20 m, with a shot and a breach',
    erro:
      moved > 20 && shots > 0 && holes > 0
        ? '—'
        : 'with no combat, the test does not exercise the simulation draws',
    passou: moved > 20 && shots > 0 && holes > 0,
  });

  const falhas = cases.filter((c) => !c.passou).length;
  return { passou: falhas === 0, total: cases.length, falhas, cases };
}
